#!/usr/bin/env python3
"""
Bulk-load the shared retail CSVs into Oracle XE.

This is the Oracle equivalent of postgres/seed/load_bulk.sql: same source
CSVs (generated once by postgres/seed/generate_data.py), same natural-key
FK resolution (customer_code, sku, order_number), different mechanics
because Oracle XE has no \\copy/COPY and IDENTITY columns don't let us
pre-assign PKs the way SERIAL does with explicit inserts.

Uses python-oracledb in "thin" mode -- no Oracle Instant Client required.

Usage:
    pip install -r oracle/seed/requirements.txt
    python oracle/seed/load_oracle.py

Reads connection settings from the project .env (ORACLE_* keys) or
environment variables, with the same defaults as docker-compose.oracle.yml.
"""

from __future__ import annotations

import csv
import os
import sys
import time
from datetime import date, datetime
from pathlib import Path

import oracledb

PROJECT_ROOT = Path(__file__).resolve().parents[2]
# Single source of truth for seed data -- generated by
# postgres/seed/generate_data.py and shared by both database loaders.
DATA_DIR = PROJECT_ROOT / "postgres" / "seed" / "data"

BATCH_SIZE = 2000


def load_env_file() -> None:
    """Lightweight .env loader (no python-dotenv dependency)."""
    env_path = PROJECT_ROOT / ".env"
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip())


def get_connection() -> oracledb.Connection:
    user = os.environ.get("ORACLE_APP_USER", "sqlstudent")
    password = os.environ.get("ORACLE_PASSWORD", "OraclePractice2024!")
    host = os.environ.get("ORACLE_HOST", "localhost")
    port = os.environ.get("ORACLE_PORT", "1521")
    service = os.environ.get("ORACLE_SERVICE", "XEPDB1")
    dsn = f"{host}:{port}/{service}"

    print(f"Connecting to {user}@{dsn} ...")
    last_error: Exception | None = None
    for attempt in range(1, 11):
        try:
            return oracledb.connect(user=user, password=password, dsn=dsn)
        except oracledb.Error as exc:
            last_error = exc
            print(f"  attempt {attempt}/10 failed ({exc}); retrying in 5s...")
            time.sleep(5)
    raise SystemExit(f"Could not connect to Oracle after 10 attempts: {last_error}")


def read_csv(name: str) -> list[dict]:
    path = DATA_DIR / name
    if not path.exists():
        raise SystemExit(
            f"Missing {path}. Run postgres/seed/generate_data.py first "
            "(it produces the CSVs both loaders consume)."
        )
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def s(value: str | None) -> str | None:
    """Empty CSV string -> NULL."""
    return value if value not in (None, "") else None


def n(value: str | None, cast=float):
    value = s(value)
    return cast(value) if value is not None else None


def dt(value: str | None) -> datetime | None:
    value = s(value)
    return datetime.fromisoformat(value) if value is not None else None


def d(value: str | None) -> date | None:
    value = s(value)
    return date.fromisoformat(value) if value is not None else None


def chunked(rows: list, size: int):
    for i in range(0, len(rows), size):
        yield rows[i : i + size]


def executemany_batched(cursor, sql: str, rows: list[tuple], label: str) -> None:
    total = len(rows)
    done = 0
    for batch in chunked(rows, BATCH_SIZE):
        cursor.executemany(sql, batch)
        done += len(batch)
        print(f"  {label}: {done}/{total}", end="\r")
    print(f"  {label}: {done}/{total} done")


def fetch_id_map(cursor, sql: str) -> dict[str, int]:
    cursor.execute(sql)
    return {code: pk for pk, code in cursor}


def main() -> None:
    load_env_file()

    print("Loading CSVs from", DATA_DIR)
    customers = read_csv("customers.csv")
    products = read_csv("products.csv")
    sales_orders = read_csv("sales_orders.csv")
    sales_order_items = read_csv("sales_order_items.csv")
    inventory = read_csv("inventory.csv")
    payments = read_csv("payments.csv")

    conn = get_connection()
    conn.autocommit = False
    cursor = conn.cursor()

    # Safety check: bulk-generated customer codes look like CUST-00001.
    # DQ fixture rows (CUST-DQ-001) are inserted separately by
    # oracle/init/03_data_quality.sql and don't collide with this check.
    cursor.execute("SELECT COUNT(*) FROM customers WHERE customer_code LIKE 'CUST-0%'")
    (already_loaded,) = cursor.fetchone()
    if already_loaded > 0:
        raise SystemExit(
            f"customers already has {already_loaded} bulk-loaded rows. "
            "Reset the Oracle volume first (docker compose -f docker-compose.oracle.yml down -v) "
            "before reloading, to avoid unique-constraint errors."
        )

    try:
        # ---------------------------------------------------------------
        # customers
        # ---------------------------------------------------------------
        rows = [
            (
                c["customer_code"],
                c["full_name"],
                s(c["email"]),
                s(c["phone"]),
                c["country"],
                c["region"],
                c["city"],
                c["sales_channel"],
                n(c["credit_limit"]),
                dt(c["created_at"]),
            )
            for c in customers
        ]
        executemany_batched(
            cursor,
            """INSERT INTO customers
               (customer_code, full_name, email, phone, country, region, city,
                sales_channel, credit_limit, created_at)
               VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10)""",
            rows,
            "customers",
        )
        conn.commit()
        customer_id_by_code = fetch_id_map(
            cursor, "SELECT customer_id, customer_code FROM customers"
        )

        # ---------------------------------------------------------------
        # products
        # ---------------------------------------------------------------
        rows = [
            (
                p["sku"],
                p["product_name"],
                n(p["category_id"], int),
                int(p["supplier_id"]),
                float(p["list_price"]),
                float(p["cost_price"]),
                1 if p["is_active"].lower() == "true" else 0,
                d(p["discontinued_at"]),
                dt(p["created_at"]),
            )
            for p in products
        ]
        executemany_batched(
            cursor,
            """INSERT INTO products
               (sku, product_name, category_id, supplier_id, list_price, cost_price,
                is_active, discontinued_at, created_at)
               VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9)""",
            rows,
            "products",
        )
        conn.commit()
        product_id_by_sku = fetch_id_map(cursor, "SELECT product_id, sku FROM products")

        # ---------------------------------------------------------------
        # sales_orders
        # ---------------------------------------------------------------
        rows = []
        skipped_orders = 0
        for o in sales_orders:
            cid = customer_id_by_code.get(o["customer_code"])
            if cid is None:
                skipped_orders += 1
                continue
            rows.append(
                (
                    o["order_number"],
                    cid,
                    n(o["employee_id"], int),
                    dt(o["order_date"]),
                    o["status"],
                    o["sales_channel"],
                    o["ship_region"],
                    dt(o["shipped_at"]),
                    dt(o["cancelled_at"]),
                    s(o["notes"]),
                )
            )
        executemany_batched(
            cursor,
            """INSERT INTO sales_orders
               (order_number, customer_id, employee_id, order_date, status,
                sales_channel, ship_region, shipped_at, cancelled_at, notes)
               VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10)""",
            rows,
            "sales_orders",
        )
        conn.commit()
        if skipped_orders:
            print(f"  WARNING: skipped {skipped_orders} orders with unknown customer_code")
        order_id_by_number = fetch_id_map(
            cursor, "SELECT order_id, order_number FROM sales_orders"
        )

        # ---------------------------------------------------------------
        # sales_order_items
        # ---------------------------------------------------------------
        rows = []
        skipped_items = 0
        for i in sales_order_items:
            oid = order_id_by_number.get(i["order_number"])
            pid = product_id_by_sku.get(i["sku"])
            if oid is None or pid is None:
                skipped_items += 1
                continue
            rows.append(
                (
                    oid,
                    pid,
                    int(i["quantity"]),
                    float(i["unit_price"]),
                    n(i["discount_pct"]),
                )
            )
        executemany_batched(
            cursor,
            """INSERT INTO sales_order_items
               (order_id, product_id, quantity, unit_price, discount_pct)
               VALUES (:1, :2, :3, :4, :5)""",
            rows,
            "sales_order_items",
        )
        conn.commit()
        if skipped_items:
            print(f"  WARNING: skipped {skipped_items} order items with unknown FK")

        # ---------------------------------------------------------------
        # inventory (CSV references product_id positionally, 1..N, which
        # matches SKU-00001..SKU-000N -- same trick load_bulk.sql uses)
        # ---------------------------------------------------------------
        rows = []
        skipped_inventory = 0
        for r in inventory:
            sku = f"SKU-{int(r['product_id']):05d}"
            pid = product_id_by_sku.get(sku)
            if pid is None:
                skipped_inventory += 1
                continue
            rows.append(
                (
                    pid,
                    r["warehouse_location"],
                    int(r["quantity_on_hand"]),
                    int(r["reorder_level"]),
                    dt(r["last_restocked_at"]),
                )
            )
        executemany_batched(
            cursor,
            """INSERT INTO inventory
               (product_id, warehouse_location, quantity_on_hand, reorder_level, last_restocked_at)
               VALUES (:1, :2, :3, :4, :5)""",
            rows,
            "inventory",
        )
        conn.commit()
        if skipped_inventory:
            print(f"  WARNING: skipped {skipped_inventory} inventory rows with unknown product")

        # ---------------------------------------------------------------
        # payments
        # ---------------------------------------------------------------
        rows = []
        skipped_payments = 0
        for pay in payments:
            oid = order_id_by_number.get(pay["order_number"])
            if oid is None:
                skipped_payments += 1
                continue
            rows.append(
                (
                    oid,
                    dt(pay["payment_date"]),
                    float(pay["amount"]),
                    pay["payment_method"],
                    pay["status"],
                    s(pay["reference_no"]),
                )
            )
        executemany_batched(
            cursor,
            """INSERT INTO payments
               (order_id, payment_date, amount, payment_method, status, reference_no)
               VALUES (:1, :2, :3, :4, :5, :6)""",
            rows,
            "payments",
        )
        conn.commit()
        if skipped_payments:
            print(f"  WARNING: skipped {skipped_payments} payments with unknown order_number")

    except Exception:
        conn.rollback()
        raise

    # -------------------------------------------------------------------
    # Verify row counts
    # -------------------------------------------------------------------
    print("\nRow counts:")
    checks = {
        "customers": 1000,
        "products": 500,
        "sales_orders": 5000,
    }
    all_ok = True
    for table in (
        "customers",
        "products",
        "sales_orders",
        "sales_order_items",
        "inventory",
        "payments",
    ):
        cursor.execute(f"SELECT COUNT(*) FROM {table}")
        (count,) = cursor.fetchone()
        marker = ""
        if table in checks:
            ok = count >= checks[table]
            all_ok &= ok
            marker = "  [OK]" if ok else f"  [FAIL, expected >= {checks[table]}]"
        print(f"  {table:<20} {count:>7}{marker}")

    cursor.close()
    conn.close()

    if not all_ok:
        print("\nWARNING: some tables did not meet minimum row counts.")
        sys.exit(1)

    print("\nDone. Oracle XE is loaded with the full retail dataset.")


if __name__ == "__main__":
    main()
